//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DayLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R3, L2, L2, R4, L1, R2, R3, R4, L2, R4, L2, L5, L1, R5, R2, R2, L1, R4, R1, L5, L3, R4, R3, R1, L1, L5, L4, L2, R5, L3, L4, R3, R1, L3, R1, L3, R3, L4, R2, R5, L190, R2, L3, R47, R4, L3, R78, L1, R3, R190, R4, L3, R4, R2, R5, R3, R4, R3, L1, L4, R3, L4, R1, L4, L5, R3, L3, L4, R1, R2, L4, L3, R3, R3, L2, L5, R1, L4, L1, R5, L5, R1, R5, L4, R2, L2, R1, L5, L4, R4, R4, R3, R2, R3, L1, R4, R5, L2, L5, L4, L1, R4, L4, R4, L4, R1, R5, L1, R1, L5, R5, R1, R1, L3, L1, R4, L1, L4, L4, L3, R1, R4, R1, R1, R2, L5, L2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AOC2016_Day01_Input {
            get {
                return ResourceManager.GetString("AOC2016_Day01_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRLLRLLRULLRUUUDRDLDDLLLDDDDDUUURRRRUUDLRULURRRDRUDRUUDDRUDLLLRLDDDUDRDDRRLLLLRLRLULUURDRURRUULDRRDUDURRUURURDLURULLDUDRDLUUUUDDURRLLLUDLDLRDRRRDULLDLDULLDRLDLDURDLRRULLDDLDRLLLUDDLLRDURULLDDDDDUURURLRLRRDUURUULRLLLULLRLULLUUDRRLLDURLDDDDULUUDLUDDDULRLDURDDRUUDRRUUURLLLULURUDRULDRDUDUDRRDDULRURLLRRLRRLLDLULURDRDRULDRDRURUDLLRRDUUULDDDUURDLULDLRLLURRURLLUDURDDRUDRDLLLLDLRLDLDDRDRRDUUULLUULRRDLURLDULLDLDUUUULLLDRURLRULLULRLULUURLLRDDRULDULRLDRRURLURUDLRRRLUDLDUULULLURLDDUDDLLUDRUDRLDUDURRRRLRUUURLUDDUDURDUDDD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AOC2016_Day02_Input {
            get {
                return ResourceManager.GetString("AOC2016_Day02_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32941994713271959948248321975648598766826381888897682988942438326656546814128868622345259915532765786412655899591784142183893293614966739916146736263445521794139955622668181383723932139661431249144693976925872511126632178628792332267635339111288933545363532138471222514638578941598198287248279695764321918477877727328812668754697211893318822281465768329213146382213173932564719985981172896326846633552738459839338457217134978117669953677958579652221836687655174542633541111348413346313451115961316827261965747631 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AOC2017_Day01_Input {
            get {
                return ResourceManager.GetString("AOC2017_Day01_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 493	458	321	120	49	432	433	92	54	452	41	461	388	409	263	58
        ///961	98	518	188	958	114	1044	881	948	590	972	398	115	116	451	492
        ///76	783	709	489	617	72	824	452	748	737	691	90	94	77	84	756
        ///204	217	90	335	220	127	302	205	242	202	259	110	118	111	200	112
        ///249	679	4015	106	3358	1642	228	4559	307	193	4407	3984	3546	2635	3858	924
        ///1151	1060	2002	168	3635	3515	3158	141	4009	3725	996	142	3672	153	134	1438
        ///95	600	1171	1896	174	1852	1616	928	79	1308	2016	88	80	1559	1183	107
        ///187	567	432	553	69	38	131	166	93	132	498	153	4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AOC2017_Day02_Input {
            get {
                return ResourceManager.GetString("AOC2017_Day02_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 361527.
        /// </summary>
        public static string AOC2017_Day03_Input {
            get {
                return ResourceManager.GetString("AOC2017_Day03_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AOC2017_Day04_Input {
            get {
                return ResourceManager.GetString("AOC2017_Day04_Input", resourceCulture);
            }
        }
    }
}
